"""Contenido fijo parte 3: Procedimientos de emergencia (Cap 5)."""


def write_proc_incendio(doc, h1, p, bullet):
    h1(doc, "CAPITULO N°5: PROCEDIMIENTOS")
    h1(doc, "INCENDIO")
    p(doc, "Un incendio corresponde a un fuego descontrolado de grandes proporciones que genera daño a las personas y a las instalaciones.")

    h1(doc, "ALARMA DE INCENDIO")
    p(doc, "El sistema de alarma del edificio opera en dos etapas para evitar evacuaciones innecesarias por falsas alarmas.")
    p(doc, "Etapa 1: PRE-ALARMA (Señal de Verificación Interna)", bold=True)
    bullet(doc, "¿Qué la activa? La activación de un único dispositivo, como un detector de humo.")
    bullet(doc, "¿Qué sucede? Se genera una alerta silenciosa únicamente en la Central de la conserjería. El personal debe verificar si es un incendio real o una falsa alarma.")
    p(doc, "Etapa 2: ALARMA CONFIRMADA (Activación de Protocolos de Emergencia)", bold=True)
    p(doc, "¿Qué la activa? La confirmación de un incendio real por parte del personal o la activación de dos o más detectores de humo o un pulsador manual de alarma.")
    p(doc, "¿Qué sucede? Se declara la emergencia y el sistema activa:")
    bullet(doc, "Llamada y Bloqueo de Ascensores: Los ascensores viajan al primer piso, abren sus puertas y quedan fuera de servicio.")
    bullet(doc, "Presurización de Escaleras: Se inyecta aire a la caja de escaleras para mantenerla libre de humo.")
    bullet(doc, "Corte de Ventilación: Se detienen los sistemas de ventilación para evitar la propagación de humo.")
    bullet(doc, "Liberación de Accesos: Se desbloquean las puertas controladas por el sistema.")
    bullet(doc, "Evacuación Focalizada: Se activa la alarma de evacuación prioritariamente en el piso del incendio y pisos adyacentes.")

    p(doc, "Protocolo de Actuación en Caso de Incendio", bold=True)
    p(doc, "Acciones del Personal del Condominio:", bold=True)
    bullet(doc, "Verificación de Alarma: Acudir inmediatamente al piso afectado para verificar la situación.")
    bullet(doc, "Confirmación y Llamada: Llamar inmediatamente a Bomberos (132) y Carabineros (133).")
    bullet(doc, "Dirección de la Emergencia: El Jefe de Emergencia se constituirá en la conserjería para dirigir los procedimientos.")
    bullet(doc, "Control de Accesos: Cese inmediato del ingreso de personas ajenas y facilitar acceso a vehículos de emergencia.")
    bullet(doc, "Gestión de la Evacuación: Activar la alarma general y guiar la evacuación por altavoz.")

    p(doc, "Acciones de los Líderes de Evacuación:", bold=True)
    bullet(doc, "Guiar la Evacuación: Al activarse la alarma, guiar a los residentes hacia la vía de evacuación.")
    bullet(doc, "Revisión de Áreas: Revisar áreas comunes del piso para asegurar que no queden personas rezagadas.")
    bullet(doc, "Punto de Reunión: Conducir al grupo hasta la Zona de Seguridad exterior.")
    bullet(doc, "Recuento e Informe: Realizar un recuento de vecinos e informar novedades al Jefe de Emergencia.")

    p(doc, "Instrucciones para Todos los Residentes:", bold=True)
    bullet(doc, "Mantenga la calma y escuche las instrucciones del personal del edificio.")
    bullet(doc, "Antes de abrir cualquier puerta, tóquela con el dorso de la mano. Si está caliente, NO LA ABRA.")
    bullet(doc, "Evacúe usando siempre las escaleras. NUNCA utilice los ascensores.")
    bullet(doc, "Si hay humo, agáchese y avance gateando. Cúbrase la boca y nariz con un paño húmedo.")
    bullet(doc, "Cierre las puertas a su paso para aislar el fuego.")
    bullet(doc, "Si su ropa se prende, ¡NO CORRA! Deténgase, tírese al suelo, cúbrase el rostro y ruede.")
    bullet(doc, "Una vez fuera, diríjase a la Zona de Seguridad y no regrese hasta que las autoridades lo autoricen.")

    p(doc, "Procedimiento en Caso de Quedar Atrapado:", bold=True)
    bullet(doc, "Si la vía de evacuación está bloqueada, su departamento es el lugar más seguro.")
    bullet(doc, "NO ABRA LA PUERTA. Selle la puerta con toallas o sábanas húmedas.")
    bullet(doc, "Llame a conserjería o Bomberos (132) para informar su ubicación exacta.")
    bullet(doc, "Hágase visible desde una ventana con un paño llamativo para que los equipos de rescate lo vean.")


def write_proc_sismo(doc, h1, p, bullet):
    h1(doc, "SISMO")
    p(doc, "Vivir en un país sísmico como Chile nos obliga a estar siempre preparados.")
    p(doc, "ANTES DEL SISMO: La Preparación es Clave", bold=True)
    bullet(doc, "Identifique Zonas de Seguridad dentro de su departamento (bajo vigas, mesas firmes).")
    bullet(doc, "Asegure sus Pertenencias: Fije muebles altos a los muros. Ubique objetos pesados en partes bajas.")
    bullet(doc, "Conozca los Suministros: Aprenda dónde están y cómo cortar las llaves de paso de agua y gas.")
    bullet(doc, "Prepare su Kit de Emergencia: agua, comida no perecible, linternas, radio, botiquín, documentos.")

    p(doc, "DURANTE EL SISMO: Mantenga la Calma y Protéjase", bold=True)
    bullet(doc, "Aplique el método \"Agáchate, Cúbrete y Afírmate\".")
    bullet(doc, "Aléjese de ventanas, espejos, lámparas y objetos que puedan caer.")
    bullet(doc, "Permanezca dentro del edificio. La estructura está diseñada para resistir sismos.")
    bullet(doc, "NO utilice los ascensores.")

    p(doc, "DESPUÉS DEL SISMO: Evalúe y Actúe con Cuidado", bold=True)
    bullet(doc, "Verifique si hay lesionados y preste primeros auxilios si está capacitado.")
    bullet(doc, "Revise su entorno. Si huele a gas, no encienda luces, cierre la llave y ventile.")
    bullet(doc, "Prepárese para las réplicas.")
    bullet(doc, "Use zapatos resistentes para protegerse de vidrios rotos.")
    p(doc, "NO evacúe el edificio a menos que:")
    bullet(doc, "Las autoridades o el personal del condominio lo indiquen.")
    bullet(doc, "Exista un principio de incendio que no pueda controlar.")
    bullet(doc, "El edificio presente daños estructurales evidentes.")

    h1(doc, "RESPONSABILIDADES ESPECIFICAS")
    p(doc, "Comité de Administración y/o Administrador(a):", bold=True)
    bullet(doc, "Evaluar la situación general post-sismo para tomar decisiones estratégicas.")
    bullet(doc, "Disponer la evacuación total o parcial si la seguridad está en riesgo.")
    bullet(doc, "Gestionar la revisión técnica de los sistemas vitales del edificio.")
    p(doc, "Jefe de Emergencia y Personal del Condominio:", bold=True)
    bullet(doc, "Mantener la calma y transmitir tranquilidad a los residentes.")
    bullet(doc, "Realizar inspección visual preliminar de áreas comunes.")
    bullet(doc, "Verificar estado de ascensores y si hay personas atrapadas.")
    p(doc, "Líderes de Evacuación:", bold=True)
    bullet(doc, "Verificar el estado de sus vecinos en el piso.")
    bullet(doc, "Comprobar que las puertas no estén atascadas por el movimiento sísmico.")
    bullet(doc, "En caso de orden de evacuación, liderar a los residentes hacia la Zona de Seguridad.")


def write_proc_bomba(doc, h1, p, bullet):
    h1(doc, "LLAMADO AMENAZANTE POR ARTEFACTO EXPLOSIVO")
    p(doc, "Una amenaza de bomba es un acto delictual grave que debe ser manejado con la máxima seriedad y calma.")
    p(doc, "Medidas Preventivas:", bold=True)
    bullet(doc, "Vigilancia de Áreas Comunes: Reportar cualquier actividad o persona sospechosa.")
    bullet(doc, "Atención a Paquetes y Objetos Extraños: Reportar inmediatamente cualquier paquete sin destinatario.")
    p(doc, "Si Usted Recibe la Llamada:", bold=True)
    bullet(doc, "Mantenga la Calma y Escuche. No Cuelgue.")
    bullet(doc, "Tome Nota: Anote la hora exacta, las palabras textuales y detalles del llamante.")
    bullet(doc, "Avise Inmediatamente al Jefe de Emergencia y llame a Carabineros (133).")
    p(doc, "Ante Hallazgo de un Objeto Sospechoso:", bold=True)
    bullet(doc, "¡NO TOCAR, NO MOVER, NO MANIPULAR!")
    bullet(doc, "Aléjese y aleje a todas las personas del lugar.")
    bullet(doc, "Avise a conserjería y llame a Carabineros (133).")
    bullet(doc, "La evacuación será dirigida exclusivamente por Carabineros de Chile.")


def write_proc_asalto(doc, h1, p, bullet):
    h1(doc, "ASALTO")
    p(doc, "El objetivo es salvaguardar la vida y la integridad física de los residentes y personal del edificio.")
    p(doc, "Medidas Preventivas (ANTES):", bold=True)
    bullet(doc, "Manténgase Atento al Entorno al entrar o salir del condominio.")
    bullet(doc, "Comunicación es Clave: Si nota algo inusual, informe a conserjería.")
    bullet(doc, "Sea Discreto: Evite hacer ostentación de objetos de valor.")
    bullet(doc, "Asegure los Accesos: Verifique que las puertas queden bien cerradas.")
    p(doc, "Acciones Durante el Asalto (DURANTE):", bold=True)
    bullet(doc, "¡MANTENGA LA CALMA! Su vida es lo más valioso. No intente actos heroicos.")
    bullet(doc, "Obedezca las Instrucciones de los asaltantes sin discutir.")
    bullet(doc, "Memorice rasgos y detalles clave: estatura, vestimenta, voz, vehículos.")
    bullet(doc, "En Caso de Disparos: Tírese al suelo y cúbrase la cabeza.")
    p(doc, "Acciones Inmediatas (DESPUÉS):", bold=True)
    bullet(doc, "Verifique que los delincuentes se han ido.")
    bullet(doc, "Contacte a Carabineros (133) o PDI (134) inmediatamente.")
    bullet(doc, "NO ALTERE LA ESCENA DEL CRIMEN.")
    bullet(doc, "Asista a los heridos y solicite ambulancia al SAMU (131) si es necesario.")


def write_proc_electrica(doc, h1, p, bullet):
    h1(doc, "FALLAS ELÉCTRICAS")
    p(doc, "Medidas Iniciales para Residentes:", bold=True)
    bullet(doc, "Mantenga la calma. El edificio cuenta con iluminación de emergencia.")
    bullet(doc, "Utilice linternas. NO UTILICE VELAS ni fuentes de llama abierta.")
    bullet(doc, "Desenchufe equipos electrónicos delicados.")
    bullet(doc, "Mantenga cerradas las puertas del refrigerador y congelador.")
    bullet(doc, "NO USE LOS ASCENSORES. Diríjase siempre por las escaleras.")
    p(doc, "Protocolo para el Personal del Edificio:", bold=True)
    bullet(doc, "Verificar el Origen del Corte: Determinar si la falla es interna o externa.")
    bullet(doc, "Verificar Equipos de Emergencia: Asegurarse de que el grupo electrógeno se active.")
    bullet(doc, "Informar a los Residentes sobre la causa y tiempo estimado de reposición.")
    bullet(doc, "Realizar Rondas de Seguridad en áreas comunes, escaleras y subterráneos.")


def write_proc_agua(doc, h1, p, bullet):
    h1(doc, "CORTE DE SUMINISTRO DE AGUA POTABLE")
    p(doc, "Medidas de Preparación para Residentes:", bold=True)
    bullet(doc, "Mantener una reserva de emergencia: Al menos 3 litros por persona por día.")
    bullet(doc, "Ante cortes programados: Junte agua en recipientes limpios y tapados.")
    p(doc, "Acciones para Residentes (DURANTE):", bold=True)
    bullet(doc, "Haga un uso racional y moderado del agua.")
    bullet(doc, "Evite actividades de alto consumo (lavar ropa, duchas largas).")
    bullet(doc, "Mantenga las llaves de paso bien cerradas cuando no las use.")
    p(doc, "Protocolo para el Personal del Edificio:", bold=True)
    bullet(doc, "Detección y Diagnóstico: Verificar si la causa es interna o externa.")
    bullet(doc, "¡Prioridad Absoluta! La reserva de agua para incendios NO DEBE SER UTILIZADA PARA CONSUMO.")
    bullet(doc, "Comunicar y actualizar constantemente a los residentes.")


def write_proc_gas(doc, h1, p, bullet):
    h1(doc, "FUGA DE GAS / EMERGENCIA POR GAS")
    p(doc, "Medidas de Prevención:", bold=True)
    p(doc, "Para la Administración: Mantener al día la inspección periódica de las redes de gas (certificación SEC).")
    p(doc, "Para los Residentes: Conocer la ubicación de la llave de paso de gas. Asegurar que las rejillas de ventilación no estén obstruidas.")
    p(doc, "Acciones para Residentes (si huele a gas):", bold=True)
    p(doc, "¡NO GENERE NINGUNA CHISPA! Esta es la regla más importante.")
    bullet(doc, "NO encienda ni apague luces.")
    bullet(doc, "NO enchufe ni desenchufe aparatos eléctricos.")
    bullet(doc, "NO use su teléfono celular dentro del área con olor a gas.")
    bullet(doc, "Ventile Inmediatamente: Abra todas las puertas y ventanas.")
    bullet(doc, "Corte el Gas si es seguro hacerlo.")
    bullet(doc, "Evacúe Inmediatamente. Desde un lugar seguro, llame a Bomberos (132).")
    p(doc, "Protocolo para el Personal:", bold=True)
    bullet(doc, "¡CORTE GENERAL DE GAS PRIMERO! Cerrar la válvula de corte general.")
    bullet(doc, "¡CORTE GENERAL ELÉCTRICO DESPUÉS!")
    bullet(doc, "Activar la Alarma de Evacuación y Llamar a Bomberos (132).")
    bullet(doc, "Nadie podrá reingresar hasta que Bomberos y la empresa de gas lo autoricen.")


def write_proc_inundacion(doc, h1, p, bullet):
    h1(doc, "INUNDACIÓN / FUGA DE AGUA")
    p(doc, "Medidas de Prevención:", bold=True)
    bullet(doc, "Para la Administración: Mantenimiento periódico de canaletas, desagües y sistemas de bombas de agua.")
    bullet(doc, "Para los Residentes: Conocer la ubicación de las llaves de paso de agua de su departamento.")
    p(doc, "Acciones para Residentes:", bold=True)
    bullet(doc, "Aviso Inmediato a conserjería.")
    bullet(doc, "Corte el Agua si la fuga es en su departamento.")
    bullet(doc, "¡MÁXIMA PRECAUCIÓN ELÉCTRICA! Si el agua está cerca de enchufes o tableros, NO SE ACERQUE.")
    bullet(doc, "No Utilice los Ascensores si la inundación afecta áreas comunes.")
    p(doc, "Protocolo para el Personal:", bold=True)
    bullet(doc, "Identificar y Controlar la Fuente: Detener el flujo de agua.")
    bullet(doc, "¡SEGURIDAD ELÉCTRICA PRIMERO! Cortar el suministro eléctrico de las áreas afectadas.")
    bullet(doc, "Asegurar los Ascensores enviándolos a pisos superiores.")
    bullet(doc, "Iniciar la Extracción de Agua.")
